version: '3.7'
services:
  mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - disxt-mongodb-data:/data/db
      networks: 
        - disxt
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_URL: "mongodb://mongodb:27017/disxt"
      LOG_LABEL: "disxt_api"
      LOG_LEVEL: "debug"
      PORT: 3000
      HOSTNAME: "localhost"
      JWT_SECRET: "secret"
      JWT_EXPIRY: 86400
    ports:
      - "3000:3000"
    networks: 
      - disxt
volumes: 
  disxt-mongodb-data:
    name: disxt_mongodb_data

networks: 
  disxt:
    name: disxt_local
    driver: bridge